// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBshuG_1Sj4T5Rgas1zDD4hQor0pzrZGvM',
    appId: '1:1079894108031:web:8c9bd120a497d12a521c4a',
    messagingSenderId: '1079894108031',
    projectId: 'e-com-afcfe',
    authDomain: 'e-com-afcfe.firebaseapp.com',
    storageBucket: 'e-com-afcfe.appspot.com',
    measurementId: 'G-HDJ3FSV7EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCOvL8or_vs2V_C_cTdgYRWQn3ZRQFiLo',
    appId: '1:1079894108031:android:6112b1e0052ed202521c4a',
    messagingSenderId: '1079894108031',
    projectId: 'e-com-afcfe',
    storageBucket: 'e-com-afcfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1JMehXu3lZkD2Yt56oZJaFMSGpZht-Ks',
    appId: '1:1079894108031:ios:d841378a8b674bf0521c4a',
    messagingSenderId: '1079894108031',
    projectId: 'e-com-afcfe',
    storageBucket: 'e-com-afcfe.appspot.com',
    iosClientId: '1079894108031-2uakko6atqahn8tgug26rfrbegou5e4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1JMehXu3lZkD2Yt56oZJaFMSGpZht-Ks',
    appId: '1:1079894108031:ios:3773516580e76ca8521c4a',
    messagingSenderId: '1079894108031',
    projectId: 'e-com-afcfe',
    storageBucket: 'e-com-afcfe.appspot.com',
    iosClientId: '1079894108031-hl8cpj3plsqshab25a4oo6goueluv6e9.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCom.RunnerTests',
  );
}
